# cicd
name: deploy-main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      # Use Docker login GitHub Action
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build a Docker image of your application and tag the image
      - name: Build container image
        run: docker build -t ${{ secrets.DOCKER_USER }}/untoldcrime:latest .

      # Push image to Docker Hub
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/untoldcrime:latest
